# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  twig:
    mode: lazy

  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: "media/cache"

  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/assets"

  filter_sets:
    cache: ~

    carousel_main:
      quality: 75
      format: webp
      filters:
        thumbnail: { size: [800, 640], mode: outbound }

    carousel_thumb:
      quality: 70
      format: webp
      filters:
        thumbnail: { size: [100, 60], mode: inset }
